# Generated by Django 4.1.5 on 2023-01-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='car_type',
            field=models.CharField(default='', max_length=150),
        ),
    ]
